version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
        - POSTGRES_USER=administrator
        - POSTGRES_PASSWORD=administrator
        - POSTGRES_DB=university_db

volumes:
  postgres_data: